[package]
name = "nickel-jwt-session"
version = "0.1.0"
authors = ["Rasmus Kaj <kaj@kth.se>"]

[dependencies]
nickel = "*"
plugin = "*"
typemap = "*"
rustc-serialize = "*"
jwt = "*"
cookie = "*"
rust-crypto = "*"
hyper = "0.8.1"
